#define TK_OR                               1
#define TK_AND                              2
#define TK_EQ                               3
#define TK_NEQ                              4
#define TK_L                                5
#define TK_G                                6
#define TK_LEQ                              7
#define TK_GEQ                              8
#define TK_PLUS                             9
#define TK_MINUS                           10
#define TK_MUL                             11
#define TK_DIV                             12
#define TK_MOD                             13
#define TK_NOT                             14
#define TK_EXP                             15
#define TK_TERMINATION                     16
#define TK_UNINITIALIZED                   17
#define TK_WARNING                         18
#define TK_DOT                             19
#define TK_EOS                             20
#define TK_NL                              21
#define TK_SCOLON                          22
#define TK_DO                              23
#define TK_END                             24
#define TK_ASSIG                           25
#define TK_GLOBAL                          26
#define TK_IDENT                           27
#define TK_LOCAL                           28
#define TK_WHILE                           29
#define TK_REPEAT                          30
#define TK_UNTIL                           31
#define TK_FOR                             32
#define TK_IN                              33
#define TK_IF                              34
#define TK_THEN                            35
#define TK_ELSE                            36
#define TK_ELSEIF                          37
#define TK_RETURN                          38
#define TK_NEXT                            39
#define TK_BREAK                           40
#define TK_CLASS                           41
#define TK_PL                              42
#define TK_PR                              43
#define TK_DEF                             44
#define TK_COMMA                           45
#define TK_STRING                          46
#define TK_SBL                             47
#define TK_SBR                             48
#define TK_CBL                             49
#define TK_CBR                             50
#define TK_NIL                             51
#define TK_FALSE                           52
#define TK_TRUE                            53
#define TK_INT                             54
#define TK_REAL                            55
#define TK_COLON                           56
#define TK_PIPE                            57
